set(headers ${headers}
	src/PCH.h
	src/GameForms.h
	src/Random.h
	src/Script.h
	src/Singleton.h
	src/Acheron/Animation/Animation.h
	src/Acheron/Defeat.h
	src/Acheron/EventSink.h
	src/Acheron/Hooks/Hooks.h
	src/Acheron/Hooks/Processing.h
	src/Acheron/Interface/CustomMenu.h
	src/Acheron/Interface/HunterPride.h
	src/Acheron/Interface/Interface.h
	src/Acheron/Misc.h
	src/Acheron/Resolution.h
	src/Acheron/Validation.h
	src/Papyrus/Config.h
	src/Papyrus/Events.h
	src/Papyrus/Functions.h
	src/Serialization/EventManager.h
	src/Serialization/Serialize.h
	src/Serialization/Settings.h
)
